package hibernate.dataobjects;
// Generated Feb 8, 2016 7:33:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name="user_info"
    ,catalog="mydb"
)
public class UserInfo  implements java.io.Serializable {


     private Integer userInfoId;
     private String firstName;
     private String lastName;
     private String address;
     private String postalCode;
     private String city;
     private Set userses = new HashSet(0);

    public UserInfo() {
    }

    public UserInfo(String firstName, String lastName, String address, String postalCode, String city, Set userses) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.postalCode = postalCode;
       this.city = city;
       this.userses = userses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_info_id", unique=true, nullable=false)
    public Integer getUserInfoId() {
        return this.userInfoId;
    }
    
    public void setUserInfoId(Integer userInfoId) {
        this.userInfoId = userInfoId;
    }

    
    @Column(name="first_name", length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="address", length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="postal_code", length=45)
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    
    @Column(name="city", length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userInfo")
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


