package hibernate.dataobjects;
// Generated 23-Mar-2016 6:16:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConversationMessage generated by hbm2java
 */
@Entity
@Table(name="conversation_message"
    ,catalog="mydb"
)
public class ConversationMessage  implements java.io.Serializable {


     private Integer conversationMessageId;
     private Conversation conversation;
     private Users users;
     private String message;
     private Date timeStamp;

    public ConversationMessage() {
    }

	
    public ConversationMessage(Conversation conversation, Users users) {
        this.conversation = conversation;
        this.users = users;
    }
    public ConversationMessage(Conversation conversation, Users users, String message, Date timeStamp) {
       this.conversation = conversation;
       this.users = users;
       this.message = message;
       this.timeStamp = timeStamp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="conversation_message_id", unique=true, nullable=false)
    public Integer getConversationMessageId() {
        return this.conversationMessageId;
    }
    
    public void setConversationMessageId(Integer conversationMessageId) {
        this.conversationMessageId = conversationMessageId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="conversation_id_fk", nullable=false)
    public Conversation getConversation() {
        return this.conversation;
    }
    
    public void setConversation(Conversation conversation) {
        this.conversation = conversation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id_fk", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="message")
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_stamp", length=19)
    public Date getTimeStamp() {
        return this.timeStamp;
    }
    
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }




}


