package hibernate.dataobjects;
// Generated Mar 17, 2016 2:29:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name="groups"
    ,catalog="mydb"
)
public class Groups  implements java.io.Serializable {


     private Integer groupId;
     private String groupname;
     private String description;
     private GroupLocations groupLocations;
     private Set usersGroupses = new HashSet(0);

    public Groups() {
    }

	
    public Groups(String groupname) {
        this.groupname = groupname;
    }
    public Groups(String groupname, String description, GroupLocations groupLocations, Set usersGroupses) {
       this.groupname = groupname;
       this.description = description;
       this.groupLocations = groupLocations;
       this.usersGroupses = usersGroupses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="group_id", unique=true, nullable=false)
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    
    @Column(name="groupname", nullable=false, length=100)
    public String getGroupname() {
        return this.groupname;
    }
    
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="groups")
    public GroupLocations getGroupLocations() {
        return this.groupLocations;
    }
    
    public void setGroupLocations(GroupLocations groupLocations) {
        this.groupLocations = groupLocations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="groups")
    public Set getUsersGroupses() {
        return this.usersGroupses;
    }
    
    public void setUsersGroupses(Set usersGroupses) {
        this.usersGroupses = usersGroupses;
    }




}


