package hibernate.dataobjects;
// Generated 23-Mar-2016 6:16:41 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GroupMessages generated by hbm2java
 */
@Entity
@Table(name="group_messages"
    ,catalog="mydb"
)
public class GroupMessages  implements java.io.Serializable {


     private Integer messageId;
     private Groups groups;
     private int senderUserId;
     private int receiverUserId;
     private String messageTitle;
     private String messageContent;
     private Boolean messageReadStatus;
     private String messageDate;

    public GroupMessages() {
    }

	
    public GroupMessages(Groups groups, int senderUserId, int receiverUserId) {
        this.groups = groups;
        this.senderUserId = senderUserId;
        this.receiverUserId = receiverUserId;
    }
    public GroupMessages(Groups groups, int senderUserId, int receiverUserId, String messageTitle, String messageContent, Boolean messageReadStatus, String messageDate) {
       this.groups = groups;
       this.senderUserId = senderUserId;
       this.receiverUserId = receiverUserId;
       this.messageTitle = messageTitle;
       this.messageContent = messageContent;
       this.messageReadStatus = messageReadStatus;
       this.messageDate = messageDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="message_id", unique=true, nullable=false)
    public Integer getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="group_id_fk", nullable=false)
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }

    
    @Column(name="sender_user_id", nullable=false)
    public int getSenderUserId() {
        return this.senderUserId;
    }
    
    public void setSenderUserId(int senderUserId) {
        this.senderUserId = senderUserId;
    }

    
    @Column(name="receiver_user_id", nullable=false)
    public int getReceiverUserId() {
        return this.receiverUserId;
    }
    
    public void setReceiverUserId(int receiverUserId) {
        this.receiverUserId = receiverUserId;
    }

    
    @Column(name="message_title", length=100)
    public String getMessageTitle() {
        return this.messageTitle;
    }
    
    public void setMessageTitle(String messageTitle) {
        this.messageTitle = messageTitle;
    }

    
    @Column(name="message_content", length=5000)
    public String getMessageContent() {
        return this.messageContent;
    }
    
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    
    @Column(name="message_read_status")
    public Boolean getMessageReadStatus() {
        return this.messageReadStatus;
    }
    
    public void setMessageReadStatus(Boolean messageReadStatus) {
        this.messageReadStatus = messageReadStatus;
    }

    
    @Column(name="message_date", length=20)
    public String getMessageDate() {
        return this.messageDate;
    }
    
    public void setMessageDate(String messageDate) {
        this.messageDate = messageDate;
    }




}


