package hibernate.dataobjects;
// Generated Feb 14, 2016 6:00:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name="groups"
    ,catalog="mydb"
)
public class Groups  implements java.io.Serializable {


     private Integer groupId;
     private String groupname;
     private String description;
     private Set usersGroupses = new HashSet(0);

    public Groups() {
    }

	
    public Groups(String groupname) {
        this.groupname = groupname;
    }
    public Groups(String groupname, String description, Set usersGroupses) {
       this.groupname = groupname;
       this.description = description;
       this.usersGroupses = usersGroupses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="group_id", unique=true, nullable=false)
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    
    @Column(name="name", nullable=false, length=100) //changed from groupname to name
    public String getGroupname() {
        return this.groupname;
    }
    
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="groups")
    public Set getUsersGroupses() {
        return this.usersGroupses;
    }
    
    public void setUsersGroupses(Set usersGroupses) {
        this.usersGroupses = usersGroupses;
    }




}


