package hibernate.dataobjects;
// Generated 11-Mar-2016 10:47:03 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * GroupLocations generated by hbm2java
 */
@Entity
@Table(name="group_locations"
    ,catalog="mydb"
)
public class GroupLocations  implements java.io.Serializable {


     private int groupIdFk;
     private Groups groups;
     private String address;
     private float latitude;
     private float longitude;

    public GroupLocations() {
    }

	
    public GroupLocations(Groups groups, float latitude, float longitude) {
        this.groups = groups;
        this.latitude = latitude;
        this.longitude = longitude;
    }
    public GroupLocations(Groups groups, String address, float latitude, float longitude) {
       this.groups = groups;
       this.address = address;
       this.latitude = latitude;
       this.longitude = longitude;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="groups"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="group_id_fk", unique=true, nullable=false)
    public int getGroupIdFk() {
        return this.groupIdFk;
    }
    
    public void setGroupIdFk(int groupIdFk) {
        this.groupIdFk = groupIdFk;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }

    
    @Column(name="address", length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="latitude", nullable=false, precision=10, scale=6)
    public float getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(float latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="longitude", nullable=false, precision=10, scale=6)
    public float getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(float longitude) {
        this.longitude = longitude;
    }




}


