package hibernate.dataobjects;
// Generated 23-Mar-2016 6:16:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name="groups"
    ,catalog="mydb"
)
public class Groups  implements java.io.Serializable {


     private Integer groupId;
     private String groupname;
     private String description;
     private String address;
     private Float latitude;
     private Float longitude;
     private Set<UsersGroups> usersGroupses = new HashSet<UsersGroups>(0);
     private Set<GroupMessages> groupMessageses = new HashSet<GroupMessages>(0);

    public Groups() {
    }

	
    public Groups(String groupname) {
        this.groupname = groupname;
    }
    public Groups(String groupname, String description, String address, Float latitude, Float longitude, Set<UsersGroups> usersGroupses, Set<GroupMessages> groupMessageses) {
       this.groupname = groupname;
       this.description = description;
       this.address = address;
       this.latitude = latitude;
       this.longitude = longitude;
       this.usersGroupses = usersGroupses;
       this.groupMessageses = groupMessageses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="group_id", unique=true, nullable=false)
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    
    @Column(name="groupname", nullable=false, length=100)
    public String getGroupname() {
        return this.groupname;
    }
    
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="address", length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="latitude", precision=10, scale=6)
    public Float getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="longitude", precision=10, scale=6)
    public Float getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="groups")
    public Set<UsersGroups> getUsersGroupses() {
        return this.usersGroupses;
    }
    
    public void setUsersGroupses(Set<UsersGroups> usersGroupses) {
        this.usersGroupses = usersGroupses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="groups")
    public Set<GroupMessages> getGroupMessageses() {
        return this.groupMessageses;
    }
    
    public void setGroupMessageses(Set<GroupMessages> groupMessageses) {
        this.groupMessageses = groupMessageses;
    }




}


