package hibernate.dataobjects;
// Generated Feb 14, 2016 6:00:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="mydb"
    , uniqueConstraints = @UniqueConstraint(columnNames="username") 
)
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String username;
     private String password;
     private String email;
     private Set usersRoleses = new HashSet(0);
     private Set usersGroupses = new HashSet(0);
     private UserInfo userInfo;

    public Users() {
    }

	
    public Users(String username, String password) {
        this.username = username;
        this.password = password;
    }
    public Users(String username, String password, String email, Set usersRoleses, Set usersGroupses, UserInfo userInfo) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.usersRoleses = usersRoleses;
       this.usersGroupses = usersGroupses;
       this.userInfo = userInfo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="username", unique=true, nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set getUsersRoleses() {
        return this.usersRoleses;
    }
    
    public void setUsersRoleses(Set usersRoleses) {
        this.usersRoleses = usersRoleses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set getUsersGroupses() {
        return this.usersGroupses;
    }
    
    public void setUsersGroupses(Set usersGroupses) {
        this.usersGroupses = usersGroupses;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="users")
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }




}


