package hibernate.dataobjects;
// Generated 23-Mar-2016 6:16:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="mydb"
    , uniqueConstraints = @UniqueConstraint(columnNames="username") 
)
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String username;
     private String password;
     private String email;
     private Set<UsersRoles> usersRoleses = new HashSet<UsersRoles>(0);
     private Set<UsersGroups> usersGroupses = new HashSet<UsersGroups>(0);
     private Set<Conversation> conversationsForUserStartId = new HashSet<Conversation>(0);
     private Set<Conversation> conversationsForUserRecieveId = new HashSet<Conversation>(0);
     private Set<ConversationMessage> conversationMessages = new HashSet<ConversationMessage>(0);
     private UserInfo userInfo;

    public Users() {
    }

	
    public Users(String username, String password) {
        this.username = username;
        this.password = password;
    }
    public Users(String username, String password, String email, Set<UsersRoles> usersRoleses, Set<UsersGroups> usersGroupses, Set<Conversation> conversationsForUserStartId, Set<Conversation> conversationsForUserRecieveId, Set<ConversationMessage> conversationMessages, UserInfo userInfo) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.usersRoleses = usersRoleses;
       this.usersGroupses = usersGroupses;
       this.conversationsForUserStartId = conversationsForUserStartId;
       this.conversationsForUserRecieveId = conversationsForUserRecieveId;
       this.conversationMessages = conversationMessages;
       this.userInfo = userInfo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="username", unique=true, nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<UsersRoles> getUsersRoleses() {
        return this.usersRoleses;
    }
    
    public void setUsersRoleses(Set<UsersRoles> usersRoleses) {
        this.usersRoleses = usersRoleses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<UsersGroups> getUsersGroupses() {
        return this.usersGroupses;
    }
    
    public void setUsersGroupses(Set<UsersGroups> usersGroupses) {
        this.usersGroupses = usersGroupses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usersByUserStartId")
    public Set<Conversation> getConversationsForUserStartId() {
        return this.conversationsForUserStartId;
    }
    
    public void setConversationsForUserStartId(Set<Conversation> conversationsForUserStartId) {
        this.conversationsForUserStartId = conversationsForUserStartId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usersByUserRecieveId")
    public Set<Conversation> getConversationsForUserRecieveId() {
        return this.conversationsForUserRecieveId;
    }
    
    public void setConversationsForUserRecieveId(Set<Conversation> conversationsForUserRecieveId) {
        this.conversationsForUserRecieveId = conversationsForUserRecieveId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<ConversationMessage> getConversationMessages() {
        return this.conversationMessages;
    }
    
    public void setConversationMessages(Set<ConversationMessage> conversationMessages) {
        this.conversationMessages = conversationMessages;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="users")
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }




}


