package hibernate.dataobjects;
// Generated Feb 7, 2016 9:57:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersGroups generated by hbm2java
 */
@Entity
@Table(name="users_groups"
    ,catalog="mydb"
)
public class UsersGroups  implements java.io.Serializable {


     private Integer usersGroupsId;
     private Groups groups;
     private Users users;
     private Boolean isLeader;

    public UsersGroups() {
    }

    public UsersGroups(Groups groups, Users users, Boolean isLeader) {
       this.groups = groups;
       this.users = users;
       this.isLeader = isLeader;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="users_groups_id", unique=true, nullable=false)
    public Integer getUsersGroupsId() {
        return this.usersGroupsId;
    }
    
    public void setUsersGroupsId(Integer usersGroupsId) {
        this.usersGroupsId = usersGroupsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="group_id")
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="is_leader")
    public Boolean getIsLeader() {
        return this.isLeader;
    }
    
    public void setIsLeader(Boolean isLeader) {
        this.isLeader = isLeader;
    }




}


