package hibernate.dataobjects;
// Generated 25-Mar-2016 11:25:17 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersRolesId generated by hbm2java
 */
@Embeddable
public class UsersRolesId  implements java.io.Serializable {


     private int userRoleId;
     private String role;

    public UsersRolesId() {
    }

    public UsersRolesId(int userRoleId, String role) {
       this.userRoleId = userRoleId;
       this.role = role;
    }
   


    @Column(name="user_role_id", nullable=false)
    public int getUserRoleId() {
        return this.userRoleId;
    }
    
    public void setUserRoleId(int userRoleId) {
        this.userRoleId = userRoleId;
    }


    @Column(name="role", nullable=false, length=16)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersRolesId) ) return false;
		 UsersRolesId castOther = ( UsersRolesId ) other; 
         
		 return (this.getUserRoleId()==castOther.getUserRoleId())
 && ( (this.getRole()==castOther.getRole()) || ( this.getRole()!=null && castOther.getRole()!=null && this.getRole().equals(castOther.getRole()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserRoleId();
         result = 37 * result + ( getRole() == null ? 0 : this.getRole().hashCode() );
         return result;
   }   


}


