package com.hibernate.dataobjects;
// Generated Feb 14, 2016 4:18:31 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name="user_info"
    ,catalog="mydb"
)
public class UserInfo  implements java.io.Serializable {


     private Integer userInfoId;
     private Users users;
     private String firstName;
     private String lastName;
     private String address;
     private String postalCode;
     private String city;

    public UserInfo() {
    }

	
    public UserInfo(Users users) {
        this.users = users;
    }
    public UserInfo(Users users, String firstName, String lastName, String address, String postalCode, String city) {
       this.users = users;
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.postalCode = postalCode;
       this.city = city;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="users"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="user_info_id", unique=true, nullable=false)
    public Integer getUserInfoId() {
        return this.userInfoId;
    }
    
    public void setUserInfoId(Integer userInfoId) {
        this.userInfoId = userInfoId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="first_name", length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="address", length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="postal_code", length=45)
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    
    @Column(name="city", length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }




}


